export type SiteData = {
    id: string;
    name: string;
    createdAt: string;
    settings: {
        email?: string;
        phone?: string;
        address?: string;
        logo?: { assetId?: string; url?: string };
        favicon?: { assetId?: string; url?: string };
        logoURL?: string;
        language?: string;
        siteName?: string;
        termsURL?: string;
        timezone?: string;
        faviconURL?: string;
        metaPixelId?: string;
        tiktokPixelId?: string;
        linkedinInsightId?: string;
        microsoftUetId?: string;
        xPixelId?: string;
        siteTagline?: string;
        socialLinks?: Record<string, string>;
        contactEmail?: string;
        contactPhone?: string;
        contactAddress?: string;
        privacyPolicyURL?: string;
        recaptchaSiteKey?: string;
        googleAnalyticsId?: string;
        googleTagManagerId?: string;
        recaptchaSecretKey?: string;
        cookieConsentEnabled?: boolean;
        darkMode?: boolean;
        headHTML?: string;
        footerHTML?: string;
    };
    languages?: string[];
    fallbackLang?: string;
    domainConfigured?: boolean;
    domain?: string;
    subdomain?: string;
    hosting?: string;

};
